export const stickerLinks = [
  {
    id: 1,
    title: "Новые",
    link: "new",
  },
  {
    id: 2,
    title: "Популярные",
    link: "popular",
  },
  {
    id: 3,
    title: "Анимированные",
    link: "animated",
  },
  {
    id: 4,
    title: "Стили",
    link: "style",
  },
  {
    id: 5,
    title: "Бесплатные",
    link: "free",
  },
];

export const coverStickers = [
  {
    id: 1,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 2,
    img: "https://i.postimg.cc/cC7SW7BX/Bees-Knees.png",
    title: "Bees Knees",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 3,
    img: "https://i.postimg.cc/52VbpSCP/Thumnail.png",
    title: "Dev Sticker Pack",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 4,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 5,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 6,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 7,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 8,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 9,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 10,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 11,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 12,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 13,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
  {
    id: 14,
    img: "https://i.postimg.cc/N09YhFk5/Halloween-Stickers.png",
    title: "Chirstmans Sticker",
    author: "Rustam Zagitov",
    price: 1,
  },
];
